import "../../styles/global.css";
import { i18n, Locale } from "../../i18n/i18nConfig";
import { ReactNode } from "react";
import Link from "next/link";
import { getDictionary } from "../../i18n/getDirctionary";
import LocaleSwitcher from "./components/LocaleSwitcher/LocaleSwitcher";
import { NavBar } from "./components/NavBar/NavBar";
import { Providers } from "../providers/providers";

export const metadata = {
  title: "Test",
  description: "Generated by create-nx-workspace"
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: { lang: Locale };
}) {
  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body>
        <Providers>
          <div className="mr-6 ml-6 max-w-screen-2xl md:ml-14 md:mr-14">
            <nav className="flex h-20 items-center justify-between md:h-28 lg:h-36">
              <div className="flex items-center gap-10">
                <Link href={"/menu"} className="text-xs uppercase text-black">
                  {dictionary.NavBarStrings.Menu}
                </Link>
                <Link href={"/cart"} className="text-xs uppercase text-black">
                  {dictionary.NavBarStrings.Cart}
                </Link>
                <NavBar dictionary={dictionary} />

                <LocaleSwitcher />
              </div>
            </nav>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
