import "../../styles/global.css";
import { i18n, Locale } from "../../i18n/i18n-config";
import { ReactNode } from "react";
import { getDictionary } from "../../i18n/get-dirctionary";
import { Providers } from "../providers/providers";
import { NavBar } from "../components/nav-bar/nav-bar";

export const metadata = {
  title: "Test",
  description: "Generated by create-nx-workspace"
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: { lang: Locale };
}) {
  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body>
        <Providers dictionary={dictionary}>{children}</Providers>
      </body>
    </html>
  );
}
