import "../styles/global.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Test",
  description: "Generated by create-nx-workspace"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
  test: string;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mr-6 ml-6 max-w-screen-2xl md:ml-14 md:mr-14">
          <nav className="flex h-20 items-center justify-between md:h-28 lg:h-36">
            <Image
              src={"/logo.svg"}
              width={85}
              height={15}
              alt={"logo"}
              className="md:h-5 md:w-28"
            />

            <div className="flex gap-10">
              <Link href={"/menu"} className="text-xs uppercase text-black">
                Menu
              </Link>
              <Link href={"/cart"} className="text-xs uppercase text-black">
                Cart
              </Link>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
