import { Module, ValidationPipe } from "@nestjs/common";
import { GraphQLModule } from "@nestjs/graphql";
import { MercuriusDriver, MercuriusDriverConfig } from "@nestjs/mercurius";
import * as path from "node:path";
import { APP_PIPE } from "@nestjs/core";
import { UserModule } from "@next-nest-boilerplate/api/feature-user";
import { HomeBlockModule } from "@next-nest-boilerplate/api/feature-home-block";

const validationProvider = {
  provide: APP_PIPE,
  useValue: new ValidationPipe()
};

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, "./autogenerated-schema.gql")
    }),
    UserModule,
    HomeBlockModule
  ],
  providers: [validationProvider]
})
export class AppModule {}
