import { Module, ValidationPipe } from "@nestjs/common";
import { GraphQLModule } from "@nestjs/graphql";
import { MercuriusDriver, MercuriusDriverConfig } from "@nestjs/mercurius";
import * as path from "node:path";
import { APP_PIPE } from "@nestjs/core";
import { AuthenticationModule } from "./auth/authentication.module";
import { UserModule } from "./user-feature/user.module";

const validationProvider = {
  provide: APP_PIPE,
  useValue: new ValidationPipe({
    skipMissingProperties: true,
    enableDebugMessages: true
  })
};

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, "./autogenerated-schema.gql")
    }),
    UserModule,
    AuthenticationModule
  ],
  providers: [validationProvider]
})
export class AppModule {}
