import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "dist/apps/api/autogenerated-schema.gql",
  overwrite: true,
  documents: ["apps/**/*gql.ts", "libs/**/*gql.ts"],
  generates: {
    "libs/web/data-access-graphql/src/lib/generated/": {
      preset: "graphql-modules",
      presetConfig: {
        baseTypesPath: "./types.ts"
      },
      plugins: ["typescript", "typescript-operations", "typescript-graphql-request"],
      config: {
        gqlImport: "graphql-request#gql",
        pureMagicComment: true,
        optimizeDocumentNode: true,
        omitOperationSuffix: true
      }
    }
  }
};
export default config;
