import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "dist/apps/api/autogenerated-schema.gql",
  overwrite: true,
  documents: ["apps/**/*gql.ts", "libs/**/*gql.ts"],
  generates: {
    "libs/web/data-access-graphql/src/lib/generated/types.ts": {
      plugins: ["typescript"]
    },
    "libs/": {
      preset: "near-operation-file",
      presetConfig: {
        extension: ".gen.ts",
        baseTypesPath: "web/data-access-graphql/src/lib/generated/types.ts"
      },
      plugins: ["typescript-operations", "typescript-graphql-request"],
      config: {
        gqlImport: "graphql-request#gql",
        pureMagicComment: true,
        optimizeDocumentNode: true,
        omitOperationSuffix: true
      }
    }
  }
};
export default config;
